HOME = '/home/sheng/sheng-eatamath/S3A'
info_dir = f'{HOME}/sssa/breeds_hier/modified'
root_imagenet = f'{HOME}/dataset/imagenet-img/'
root_imagenet_val = f'{HOME}/dataset/imagenet-val-raw/'
vocab_fpath=f'{HOME}/dataset/wordnet_nouns.pkl'
output_dir = f'{HOME}/MUST-output'
vocab_dir = f'{HOME}/sssa/ipynb/cache/vocabulary'